version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: mpt-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www/html
    restart: always
    networks:
      - mpt-site-network

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./www:/var/www/html
    entrypoint: sh -c "trap exit TERM; while :; do certbot renew --webroot -w /var/www/html --post-hook 'nginx -s reload'; sleep 12h & wait $${!}; done"
    networks:
      - mpt-site-network


networks:
  mpt-site-network:
    external: true
